# Spring boot config
spring:
  profiles:
    active: development
  
  #Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/simple-crud-db
    username: admin
    password: admin123
  #JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  ##Logger configuration
  logging:
    pattern:
      console: "%d %-5level %logger: %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug

  ## server

  server:
    port: 8880
